### ISSUE TITLE
Possibility to trigger syntax highlight for different file name

### ISSUE THREAD

**Issue by MSavisko** [orta/vscode-ios-common-files#4]
Hi!

**Problem:**
Sometimes we need to separate Fastfile for two different files. One for logic, another for Utils.
But plugin and VS-code do not highlight files with name like Fastfile.Utils, FastfileUtils or UtilsFastfile.

**Solution:**
Add filenamePatterns and activationEvents for package.json

PR attached.

**Comment by orta** [comment]
Shipped as 1.0.5
